---
# install_python-apt/tasks/main.yml

- name: 'Install python-apt on Debian 10 or older'
  raw: 'apt-get update && apt-get -y install python-apt'
  when:
    - 'ansible_distribution == "Debian"'
    - 'ansible_distribution_major_version|int <= 10'
  register: python_apt_debian
  changed_when:
    - '"is already the newest version" not in python_apt_debian.stdout'
    - '"python-apt ist schon die neueste Version" not in python_apt_debian.stdout'

- name: 'Install python3-apt on Debian 11 or newer'
  raw: 'apt-get update && apt-get -y install python3-apt'
  when:
    - 'ansible_distribution == "Debian"'
    - 'ansible_distribution_major_version|int >= 11'
  register: python3_apt_debian
  changed_when:
    - '"is already the newest version" not in python3_apt_debian.stdout'
    - '"python3-apt ist schon die neueste Version" not in python3_apt_debian.stdout'

- name: 'Install python-apt on Ubuntu 18.04 or earlier'
  raw: 'apt-get update && apt-get -y install python-apt'
  when:
    - 'ansible_distribution == "Ubuntu"'
    - 'ansible_distribution_major_version|int < 20'
  register: python_apt_ubuntu
  changed_when:
    - '"is already the newest version" not in python_apt_ubuntu.stdout'
    - '"python-apt ist schon die neueste Version" not in python_apt_ubuntu.stdout'
