---
# install_python-apt/tasks/main.yml

- name: 'Install python-apt on Debian'
  raw: 'apt-get update && apt-get -y install python-apt'
  when: 'ansible_distribution == "Debian"'
  register: python_apt_debian
  changed_when: '"is already the newest version" not in python_apt_debian.stdout and "python-apt ist schon die neueste Version" not in python_apt_debian.stdout'

- name: 'Install python-apt on Ubuntu 18.04 or earlier'
  raw: 'apt-get update && apt-get -y install python-apt'
  when: 'ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 20'
  register: python_apt_ubuntu
  changed_when: '"is already the newest version" not in python_apt_ubuntu.stdout and "python-apt ist schon die neueste Version" not in python_apt_ubuntu.stdout'
